apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: pubsub-service
    docker:
      dockerfile: ./deployment/dockerfiles/service

deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
    - name: pubsub-poc
      chartPath: ./deployment/helm-charts
      namespace: default
      values:
        image: pubsub-service
      valuesFiles:
        - ./deployment/helm-charts/values.yaml
