apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pubsub-ingreess
  annotations:
    kubernetes.io/ingress.class: "gce"
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.env }}
spec:
  backend:
    serviceName: pubsub-publisher-service
    servicePort: 80
