imports:
 - path: templates/pubsub.py
 - path: templates/gke.py

resources:
- name: pub-sub
  type: templates/pubsub.py
  properties:
    name: article-updates-topic
    subscriptions:
      - name: 'article-updates-sub'
- name: article-pubsub-cluster
  type: templates/gke.py
  properties:
    region: asia-northeast1
    clusterLocationType: Regional
    cluster:
      name: article-pubsub-cluster
      description: PubSub Article PoC Cluster
      network: default
      subnetwork: default
      locations:
        - asia-northeast1-a
      nodePools:
        - name: default
          initialNodeCount: 2
          config:
            machineType: n1-standard-1
            oauthScopes:
              - https://www.googleapis.com/auth/compute
              - https://www.googleapis.com/auth/devstorage.read_only
              - https://www.googleapis.com/auth/logging.write
              - https://www.googleapis.com/auth/monitoring
