apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
    component: pubsub-publisher-deployment
    env: {{ .Values.app.env }}
  name: pubsub-publisher
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      env: {{ .Values.app.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        component: pubsub-publisher
        env: {{ .Values.app.env }}
    spec:
      containers:
      - name: publisher
        image: {{ .Values.image }}
        imagePullPolicy: Always
        command: ["bundle"]
        args: ["exec", "ruby", "publisher.rb"]
