apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-publisher
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      env: {{ .Values.app.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        component: pubsub-publisher
        env: {{ .Values.app.env }}
    spec:
      containers:
      - name: publisher
        image: {{ .Values.image }}
        imagePullPolicy: Always
        command: ["bundle"]
        tty: true
        args: ["exec", "ruby", "publisher.rb", "-p", "80"]
        readinessProbe:
          httpGet:
            path: /healthy
            port: 80
        ports:
        - name: http
          containerPort: 80
