apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.env }}
  name: pubsub-publisher-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.app.name }}
    component: pubsub-publisher
    env: {{ .Values.app.env }}
  type: NodePort
